pointcloud_listener_node:
  ros__parameters:
    pcl_topic: "/cloud_registered_body"
    dynamic_cloud_topic: "/cloud_dynamic_body"
    dynablox_param_path: "/root/install/dynablox/assets/config.yaml" # Only works in provided container!
