pointcloud_listener_node:
  ros__parameters:
    pcl_topic: "/point_cloud_topic"
    dynamic_cloud_topic: "/dynamic_pointcloud"
    dynablox_param_path: "/root/install/dynablox/assets/config.yaml" # Only works in provided container!
